// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5Tfjc2hvl-G8PeIb8cAxMTdasTERk54Y',
    appId: '1:986221030344:web:c76880b277d771bc22eefd',
    messagingSenderId: '986221030344',
    projectId: 'artify-4200',
    authDomain: 'artify-4200.firebaseapp.com',
    storageBucket: 'artify-4200.firebasestorage.app',
    measurementId: 'G-M4NJEEPK5E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsspLN1dvC-UX0WMi2MhluRg-OpZ6hP9E',
    appId: '1:986221030344:android:557ad00a584bca2122eefd',
    messagingSenderId: '986221030344',
    projectId: 'artify-4200',
    storageBucket: 'artify-4200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_oxFKQxN7ILAESgcWQXBAxxDx_TFl1k',
    appId: '1:986221030344:ios:178747adce98124d22eefd',
    messagingSenderId: '986221030344',
    projectId: 'artify-4200',
    storageBucket: 'artify-4200.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_oxFKQxN7ILAESgcWQXBAxxDx_TFl1k',
    appId: '1:986221030344:ios:178747adce98124d22eefd',
    messagingSenderId: '986221030344',
    projectId: 'artify-4200',
    storageBucket: 'artify-4200.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5Tfjc2hvl-G8PeIb8cAxMTdasTERk54Y',
    appId: '1:986221030344:web:b57d065566d06e4222eefd',
    messagingSenderId: '986221030344',
    projectId: 'artify-4200',
    authDomain: 'artify-4200.firebaseapp.com',
    storageBucket: 'artify-4200.firebasestorage.app',
    measurementId: 'G-0ZY06MDWEL',
  );

}
